name : JLC Portfolio
description : A far-from complete portfolio for James Conkling.
keyword:
url : jameslaneconkling.github.io
baseurl : /
imageurl:
email : james.lane.conkling@gmail.com
twitter : jamesconkling
github : JamesLaneConkling
author: James Conkling
location: Washington, DC (usually)
keywords: cartography, geography, topography, web design
year: 2015
analytics: UA-58936860-1
sass:
  sass_dir: bower_components/foundation/scss
  # style: :compressed
markdown: kramdown
